#!/bin/bash

PACKAGES="gcc build-essential ntp i2c-tools vim libi2c-dev connman wireless-tools pciutils firmware-misc-nonfree vim usbutils dnsutils firmware-realtek man minicom eclipse-cdt"

apt-get -y update 
apt-get -y dist-upgrade -y

apt-get -y install $PACKAGES

