#!/bin/bash

PACKAGES="gcc build-essential ntp i2c-tools vim libi2c-dev connman wireless-tools pciutils firmware-misc-nonfree vim"

apt-get -y update
apt-get -y install $PACKAGES

#Universal dtc
#git clone https://github.com/beagleboard/bb.org-overlays
